#!/bin/sh

if [ "$#" -lt 2 ]; then
	cat <<EOF
Usage: $0 INSTALLABLE EXECUTABLE

This is an alternative to 'nix bundle' that allow specifying the executable to
run. This is handy for derivations that haven't specified meta.mainProgram, or
contain multiple programs.

EXECUTABLE can be either an absolute path (relative to the derivation path), or
a relative path (relative to the /bin subdirectory).

Example usage:

	$ ./bundle dnsutils /bin/dig # or ./bundle dnsutils dig
	$ ./dig-x86_64.AppImage -v
	DiG 9.18.14
EOF
	exit 1
fi

NA_EXE="$2"
if [ "${NA_EXE#/}" = "$NA_EXE" ]; then
	# ${NA_EXE#/} = remove / from the start of NA_EXE
	NA_EXE="/bin/$NA_EXE"
fi

NA_ROOT="$(cd "$(dirname "$0")" && pwd)"
NA_OVERLAY="$NA_ROOT/overlays/system-ld-so-conf.nix"

export NA_EXE NA_OVERLAY
nix bundle --impure --bundler "$NA_ROOT" \
	--expr '
	let
		pkgs = import <nixpkgs> {
			overlays = [ (import (builtins.getEnv "NA_OVERLAY")) ];
		};
		p = with pkgs; '"$1"';
	in {
		type = "app";
		program = "${p}/${builtins.getEnv "NA_EXE"}";
	}
	'
